### ISSUE TITLE
flutter master channel build failed

### ISSUE THREAD

**Issue by selvam920** [Baseflow/octo_image#29]
## 🐛 Bug Report

/C:/Users/sksso/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_blurhash-0.7.0/lib/src/blurhash_widget.dart(218,42): error G5FE39F1E: Type 'DecoderCallback' not found. [E:\sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by MominRaza** [comment]
@renefloor please fix this issue

https://github.com/Baseflow/flutter_cached_network_image/issues/870
